version: '3.8'

services:
  product:
    platform: linux/arm64
    build: microservices/product-service
    deploy:
      resources:
        limits:
          memory: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  recommendation:
    platform: linux/arm64
    build: microservices/recommendation-service
    deploy:
      resources:
        limits:
          memory: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  review:
    platform: linux/arm64
    build: microservices/review-service
    deploy:
      resources:
        limits:
          memory: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  product-composite:
    platform: linux/arm64
    build: microservices/product-composite-service
    deploy:
      resources:
        limits:
          memory: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      rabbitmq:
        condition: service_healthy

  mongodb:
    platform: linux/arm64
    image: mongo:4.4.2
    deploy:
      resources:
        limits:
          memory: 512m
    ports:
      - "27017:27017"
    command:
      - mongod
    healthcheck:
      test: "mongo --eval 'db.stats().ok'"
      interval: 5s
      timeout: 2s
      retries: 60

  mysql:
    platform: linux/arm64
    image: mysql:8.0
    deploy:
      resources:
        limits:
          memory: 512m
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=review-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 60

  rabbitmq:
    platform: linux/arm64
    image: rabbitmq:3.8.11-management-alpine
    deploy:
      resources:
        limits:
          memory: 512m
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 2s
      retries: 60

  eureka:
    platform: linux/arm64
    build: spring-cloud/eureka-server
    deploy:
      resources:
        limits:
          memory: 512m
    ports:
      - "8761:8761"

  gateway:
    platform: linux/arm64
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: spring-cloud/gateway
    deploy:
      resources:
        limits:
          memory: 512m
    ports:
      - "8080:8080"
