server.port: 9000
server.error.include-message: always

app:
  product-service:
    host: localhost
    port: 9001
  recommendation-service:
    host: localhost
    port: 9002
  review-service:
    host: localhost
    port: 9003

logging:
  level:
    root: INFO
    com.jolly: DEBUG

---
spring.config.activate.on-profile: docker
server.port: 8080
app:
  product-service:
    host: product
    port: 8080
  recommendation-service:
    host: recommendation
    port: 8080
  review-service:
    host: review
    port: 8080
