server.port: 9003
server.error.include-message: always

logging:
  level:
    root: INFO
    com.jolly: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring.jpa.hibernate.ddl-auto: update

spring:
  datasource:
    url: jdbc:mysql://localhost/review-db
    username: user
    password: pwd
    hikari:
      initialization-fail-timeout: 60000

---
spring.config.activate.on-profile: docker
server.port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql/review-db
